version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/scripts/blockstream_info"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/scripts/brain_wallet"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/scripts/generate_addresses"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/scripts/generate_mnemonic"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
open-pull-requests-limit: 5