[package]
name = "sign_tx"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.29"
bitcoin_hashes = "0.19"
secp256k1 = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
